# Generated by Django 5.2.3 on 2025-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_reminderfailurelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notify_type',
            field=models.CharField(choices=[('email', 'Email'), ('inapp', 'In-App'), ('sms', 'SMS')], default='email', max_length=10),
        ),
    ]
